version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: ci

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    commit-message:
      prefix: docker

  - package-ecosystem: npm
    directory: /unpub/web
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps(web)
    groups:
      vite:
        patterns:
          - "vite"
          - "vite-plugin-*"
          - "@vitejs/*"
      vue:
        patterns:
          - "vue"
          - "vue-*"
          - "@vue/*"

  - package-ecosystem: pub
    directory: /unpub
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps(unpub)

  - package-ecosystem: pub
    directory: /unpub_aws
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps(unpub_aws)
