{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "unpub.fullname" . }}
  labels:
    {{- include "unpub.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "unpub.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ default "30s" .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ default "10s" .Values.serviceMonitor.scrapeTimeout }}
{{- end }}
