#!/usr/bin/env node
// Convert the single-file Vite build at dist/index.html into a Dart constant
// the unpub server can serve directly. Run after `vite build`.

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const src = resolve(__dirname, "dist", "index.html");
const out = resolve(__dirname, "..", "lib", "src", "static", "index.html.dart");

const html = await readFile(src, "utf8");

// `r"""..."""` is a raw triple-quoted string in Dart. It permits anything
// except a literal `"""`, which Vite would never emit. We still defensively
// fail loud if it appears.
if (html.includes('"""')) {
  console.error("dist/index.html contains a triple-double-quote — aborting");
  process.exit(2);
}

const dart = `// ignore_for_file: prefer_single_quotes
// AUTO-GENERATED by web/build-to-dart.mjs. Do not edit by hand.
// Source: unpub/web/dist/index.html (Vite + Vue 3 + TypeScript build).
// Re-generate with:  cd unpub/web && pnpm install && pnpm build

const content = r"""${html}""";
`;

await mkdir(dirname(out), { recursive: true });
await writeFile(out, dart);
console.log(`wrote ${out} (${html.length.toLocaleString()} chars)`);
